### ISSUE TITLE
DI resolution error during startup.

### ISSUE THREAD

**Issue by lessismore1** [msmolka/ZNetCS.AspNetCore.IPFiltering#1]
netcoreapp2.0 where I followed the setup, but gets:

Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[ZNetCS.AspNetCore.IPFiltering.IPFilteringOptions]' from root provider.

Uses:
    <PackageReference Include="ZNetCS.AspNetCore.IPFiltering" Version="2.0.0" />

**Comment by lessismore1** [comment]
Workaround:

`        public void Configure(
            IApplicationBuilder app,
            **IOptions<IPFilteringOptions> ipFilteringOptions**,`

`            app.UseIPFiltering(**ipFilteringOptions.Value**);`

**Comment by lessismore1** [comment]
One more hack to make it work:

`        public void ConfigureServices(IServiceCollection services)
        {
            // IP filtering
            services.AddIPFiltering(Configuration.GetSection("IPFiltering"));`

**Comment by msmolka** [comment]
@lessismore1 I've changed a bit documentation:

To make it work you need to provide configuration:
Or from file
```csharp
services.AddIPFiltering(this.Configuration.GetSection("IPFiltering"));
```
or by configuring it
```csharp
services.AddIPFiltering(
        opts =>
        {
            opts.DefaultBlockLevel = DefaultBlockLevel.All;
            opts.HttpStatusCode = HttpStatusCode.NotFound;
            opts.Blacklist = new List<string> { "192.168.0.100-192.168.1.200" };
            opts.Whitelist = new List<string> { "192.168.0.10-192.168.10.20", "fe80::/10" };
        });
```
