### ISSUE TITLE
IP Filter

### ISSUE THREAD

**Issue by jherbert** [msmolka/ZNetCS.AspNetCore.IPFiltering#2]
Any objections to me submitting a pull request that adds IP filtering as a MVC filter? This would bring in a new dependencies of `Microsoft.AspNetCore.Mvc.Abstractions`.

My thoughts here would be an attribute that could be applied either at the class or method level. Something like `[IPFilter(Policy = "MyPolicy")]` This would allow for either white listing, black listing at a more granular level than at the middle ware level.

Thanks!

**Comment by msmolka** [comment]
I don't mind to any PRs, It will require review, and unit tests before accept. 
But this has to be properly incorporated with `IPFilterOptions`. The controller filter needs to override global middleware, the action one needs to override controller one and middleware.

The policy idea is rather confusing, I'm thinking it would be better to have parameters as `IPFilterOptions`. Eventually after that there can be policy. 
But policy is bigger concept, I think.
It requires allowing definition from json and from code. usage inside middleware.

**Comment by jherbert** [comment]
Thank you for the response. 

Closing this out as after initial review I don't think this feature is a good fit, especially as the use case I'm after is fairly limited.
