### ISSUE TITLE
Ignoring paths separately for each Black-listed Ip

### ISSUE THREAD

**Issue by zedo02** [msmolka/ZNetCS.AspNetCore.IPFiltering#3]
I have two Ips which I've black-listed:

"Blacklist": [ "127.0.0.1", "192.168.0.1" ]

I want to ignore paths separately for each of them:

i.e. for "127.0.0.1"
"IgnoredPaths": [ "POST:/*" ]

and for "192.168.0.1"
"IgnoredPaths": [ "GET:/*" ]

Is there any way to do that?

**Comment by msmolka** [comment]
Hello, at this moment it is not possible I'm afraid.

**Comment by msmolka** [comment]
@zedo02 I finally did the change you requested.  in version 3.0.0.

**Comment by msmolka** [comment]
done
