### ISSUE TITLE
Just parse IP ranges once

### ISSUE THREAD

**Issue by Daniel15** [msmolka/ZNetCS.AspNetCore.IPFiltering#5]
This library appears to parse the allowed IP ranges on every call to `IPAddressChecker.IsAllowed`:

https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/5440e3a86c00112b96fa336676e3dae7c97856d6/src/ZNetCS.AspNetCore.IPFiltering/Internal/IPAddressChecker.cs#L67-L68

However, the config will very rarely change between requests, so it'd be more efficient to only parse these once and reuse the same objects across requests.

**Comment by msmolka** [comment]
Done: https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/commit/139582b8de5e79ee422ebaac2e6b49bf77ca5c55
